### ISSUE TITLE
how openchat rust code doing unit test ?

### ISSUE THREAD

**Issue by q2333gh** [open-chat-labs/open-chat#4852]
recently im reading the openchat codebase.
and i found that
its really good code quality with categoriesed  layers. and easy to understand.
i found integration test yes.but didnt find unit test yet.
do you know how openchat rust code doing unit test ?

since i didnt found disscusion part or any feedback pages on https://oc.app/ .
so i post the question here hah.

**Comment by q2333gh** [comment]
since i didnt found disscusion part or  any feedback pages on https://oc.app/ .
so i post the question here hah.

**Comment by hpeebles** [comment]
Hey!
We don't have many unit tests since we prefer to opt for integration tests.
However you can find a few unit tests dotted around the codebase by searching for 'mod tests'.
For example here - https://github.com/open-chat-labs/open-chat/blob/master/backend/canisters/user_index/impl/src/model/user_map.rs#L330

**Comment by q2333gh** [comment]
thanks a lot. hope your team product going next upstairs.
