### ISSUE TITLE
Local deployment is broken

### ISSUE THREAD

**Issue by let4be** [open-chat-labs/open-chat#5480]
Trying to deploy locally and followed readme(installed dfx, npm, cc, cmake, rust)
Tip of the master branch at: https://github.com/open-chat-labs/open-chat/tree/9b9f85b16d70e8c6a56ad3bf2150821d8cebb763

However no matter what I do, I get this error eventually when running `./scripts/deploy-local.sh`(dfx is started):
```
WARN: DEPRECATION WARNING: Cannot fetch Candid interface from canister metadata, reading Candid interface from the local build artifact. In a future dfx release, we will only read candid interface from canister metadata.
WARN: Please add the following to dfx.json to store local candid file into metadata:
"metadata": [
   {
     "name": "candid:service"
   }
]
WARN: Cannot fetch Candid interface for add_token, sending arguments with inferred types.
(variant { 2_241_809_827 })
(variant { Ok = 0 : nat })
```

**Comment by let4be** [comment]
Nvm, it finished successfully but some message in the build script could be useful(warnings do not help either)

**Comment by hpeebles** [comment]
Yeah I see that warning too but everything still works.
I'll see what we can do about removing that warning or at least making it clear that things worked.
By the way upgrading User/Group/Community canisters locally is currently broken because the replica version included in DFX doesn't contain the latest chunk store code.
